### ISSUE TITLE
output.txt file created

### ISSUE THREAD

**Issue by tdodson90** [Skyofazure06/checkcoroner#1]
when running this, 2 output files are created. one is output.txt, the other is output{codec serial}.txt
[output.txt](https://github.com/tdodson90/checkcoroner/files/637795/output.txt)
[outputFV651802BBAC9.txt](https://github.com/tdodson90/checkcoroner/files/637794/outputFV651802BBAC9.txt)

**Comment by SkySai** [comment]
This only happens with batchCheckCoroner, not checkCoroner, right?

-Vincent

**Comment by tdodson90** [comment]
Happens with both.

**Comment by SkySai** [comment]
I just tested this and was able to replicate with batchCheckCoroner but not *just* running checkCoroner on an individual coroner file.

**Comment by SkySai** [comment]
CheckCoroner.sh was failing in batch mode because it was having problems passing spaces in filenames. 

fixed by changing "$1" -> "$@"
